show tables;
select * from account_managers;
select * from orders;
select * from products;

-- Q1. What is the total revenue generated by each product category?

select  products.product_category ,
round(sum(orders.total),2) as total_revenue
from orders
join products on orders.product_id=products.product_id
group by products.product_category;


-- Q2.How many unique products have been ordered?

select  distinct count(product_name)  
as uniqe_orders 
from products;

-- Q3. What is the total revenue generated each year?

select extract(year from order_date) as _year ,
sum(total) as revenue from orders
group by _year;

-- Q4. What is the date of the latest and earliest order?

 select min(order_date) as latest_order,
       max(order_date) as earliest_order
from orders;

-- Q5. What product category has the lowest average price of products?

select products.product_category , 
round(avg(orders.retail_price),1) as average_price
from products
join orders on products.product_id= orders.product_id
group by products.product_category
order by average_price
limit 1; 

-- Q6. What are the top 10 highest performing products?

select products.product_name , 
round(sum(orders.total),2) as revenue
from products
join orders on products.product_id = orders.product_id
group by products.product_name
order by  revenue desc
limit 10;

-- Q7. Show the total revenue and profit generated by each account_manager?

select manager.account_manager, 
round(sum(orders.total),2) as revenue,
round(sum(orders.cost_price)-sum(orders.total),2) as profit
from orders
join manager 
on orders.account_id=manager.account_id
group by 1;


-- Q8. What is the name  , city and account manager of the highest selling product in 2017?

SELECT product_name,
				city,
                account_manager,
                ROUND(SUM(total)) Revenue
FROM orders
JOIN products
USING(product_id)
JOIN manager
USING(account_id)
WHERE EXTRACT(year from order_date) = 2017
GROUP BY product_name, city, account_manager
ORDER BY Revenue DESC
LIMIT 1;

-- Q9. Find the mean amount spent per order by each Customer type?

select customer_type ,
avg(total) as mean_amt
from orders
group by customer_type;

-- Q10. What is the 5th highest selling product? 

select products.product_name,
round(sum(orders.total),2) as "5th_high"
from products
join orders on products.product_id = orders.product_id
group by 1
limit 1 offset 4;

/* **************************************
